 version: '3'
services:
  database:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - app
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - API_KEY = ${API_KEY}
      - MYSQL_ROOT_PASSWORD = ${DB_PASSWORD}  

  api_service:
    container_name: 'api'
    ports:
      - "5000:5000"
    command: sh -c "python -m flask run --host=0.0.0.0"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - api_service_data:/python_assignment
    depends_on:
      - database
    networks:
      - app

networks:
  app:

volumes:
  mysql_data:
  api_service_data: